version: '3.9'

services:
  db:
    container_name: postgres_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: matuamod
      POSTGRES_PASSWORD: matua335
      POSTGRES_DB: car_rental_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
